### ISSUE TITLE
model is not detecting multiple faces in the image/video

### ISSUE THREAD

**Issue by aqib11** [yinguobing/head-pose-estimation#4]

**Comment by yinguobing** [comment]
The face detector is capable of detecting multiple faces, but the mark detector only works for a single face. For multiple faces, please try to apply multiple mark detectors for each of them.

**Comment by liuyafei666** [comment]
I would want to know how to get the multiple mark detections, thank you

**Comment by marcomiglionico94** [comment]
@yinguobing @liuyafei666 I was able to run it on multiple faces. The mark detector works good on both the faces, but then when I try to draw the annotation box using the pose estimator for both faces it draw 2 of them but in wrong positions. Then as soon as one of the face disappear, the annotation box come back to the correct position. I am wondering why, since the mark are detected correctly.

To detect multiple mark, just run the mark detection on every detected face for every frame in which you do the detection.

**Comment by yinguobing** [comment]
@marcomiglionico94 
Can you post the image here?

**Comment by marcomiglionico94** [comment]
Yes I will post animage. Anyway that is happening only when I use the pose stabilization. Without that it is working with multiple faces in the same frame @yinguobing

**Comment by GreyDireWolf** [comment]
@marcomiglionico94 can you share the code?

**Comment by yinguobing** [comment]
Closed. please re-open if the issue still exist.

**Comment by junhalba** [comment]
Hello, could you know which part of the code you modified to detect multiple faces?

**Comment by junhalba** [comment]
@marcomiglionico94 
Hello, could you know which part of the code you modified to detect multiple faces?
